coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
  ignore:
    - "projects/SelfTest"
    - "cpp/tests"

codecov:
  branch: master

comment:
  layout: "reach, fags"
