from __future__ import annotations
from typing import List, Tuple, TypeVar

from typing import overload

from typing import Any

buffer = TypeVar("buffer")

def add_matrixf_matrixf(arg0: MatrixF, arg1: MatrixF) -> MatrixF: ...
def add_matrixf_vectorf(arg0: MatrixF, arg1: VectorF) -> MatrixF: ...
def add_matrixi_matrixi(arg0: MatrixI, arg1: MatrixI) -> MatrixI: ...
def add_matrixi_vectori(arg0: MatrixI, arg1: VectorI) -> MatrixI: ...
def add_vectorf_vectorf(arg0: VectorF, arg1: VectorF) -> VectorF: ...
def add_vectori_vectori(arg0: VectorI, arg1: VectorI) -> VectorI: ...
def argmax_f(arg0: MatrixF) -> VectorI: ...
def argmax_i(arg0: MatrixI) -> VectorI: ...
@overload
def dot(arg0: VectorF, arg1: VectorF) -> float: ...
@overload
def dot(arg0: MatrixF, arg1: VectorF) -> VectorF: ...
@overload
def dot(A: MatrixF, B: MatrixF, A_T: bool = ..., B_T: bool = ...) -> MatrixF: ...
@overload
def dot(*args, **kwargs) -> Any: ...
def exp(arg0: MatrixF) -> MatrixF: ...
def get(arg0: MatrixF, arg1: MatrixF) -> MatrixF: ...
def log(arg0: MatrixF) -> MatrixF: ...
def multiply_matrixf_f(arg0: MatrixF, arg1: float) -> MatrixF: ...
def multiply_matrixf_matrixf(arg0: MatrixF, arg1: MatrixF) -> MatrixF: ...
def multiply_vectorf_f(arg0: VectorF, arg1: float) -> VectorF: ...
def multiply_vectorf_vectorf(arg0: VectorF, arg1: VectorF) -> VectorF: ...
def outer_product(arg0: VectorF, arg1: VectorF) -> MatrixF: ...
def pow(arg0: MatrixF, arg1: int) -> MatrixF: ...
def softmax(arg0: MatrixF) -> MatrixF: ...
def sum(arg0: MatrixF, arg1: int) -> VectorF: ...
def transpose(arg0: MatrixF) -> MatrixF: ...

class Activation:
    NONE: Any = ...
    RELU: Any = ...
    __entries: Any = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> Any: ...
    @property
    def __doc__(self) -> Any: ...
    @property
    def __members__(self) -> Any: ...

class Conv2D:
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: Activation, arg5: bool) -> None: ...
    def backward(self, *args, **kwargs) -> Any: ...
    def bias(self) -> VectorF: ...
    def forward(self, *args, **kwargs) -> Any: ...
    def update(self, arg0: float) -> None: ...
    def weight(self) -> MatrixF: ...
    def __call__(self, *args, **kwargs) -> Any: ...

class CrossEntropyLoss:
    def __init__(self) -> None: ...
    def backward(self) -> MatrixF: ...
    def forward(self, arg0: MatrixF, arg1: VectorI) -> float: ...
    def __call__(self, arg0: MatrixF, arg1: VectorI) -> float: ...

class FeedForward:
    def __init__(self, arg0: int, arg1: int, arg2: Activation, arg3: bool, arg4: float) -> None: ...
    def backward(self, arg0: MatrixF) -> MatrixF: ...
    def bias(self) -> VectorF: ...
    def forward(self, arg0: MatrixF) -> MatrixF: ...
    def update(self, arg0: float) -> None: ...
    def weight(self) -> MatrixF: ...
    def __call__(self, arg0: MatrixF) -> MatrixF: ...

class MatrixF:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[2]]: ...
    def __getitem__(self, arg0: Tuple[int,int]) -> float: ...
    def __setitem__(self, arg0: Tuple[int,int], arg1: float) -> None: ...

class MatrixI:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[2]]: ...
    def __getitem__(self, arg0: Tuple[int,int]) -> int: ...
    def __setitem__(self, arg0: Tuple[int,int], arg1: int) -> None: ...

class Tensor3F:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[3]]: ...
    def __getitem__(self, arg0: Tuple[int,int,int]) -> int: ...
    def __setitem__(self, arg0: Tuple[int,int,int], arg1: int) -> None: ...

class Tensor3I:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[3]]: ...
    def __getitem__(self, arg0: Tuple[int,int,int]) -> int: ...
    def __setitem__(self, arg0: Tuple[int,int,int], arg1: int) -> None: ...

class Tensor4F:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[4]]: ...
    def __getitem__(self, arg0: Tuple[int,int,int,int]) -> int: ...
    def __setitem__(self, arg0: Tuple[int,int,int,int], arg1: int) -> None: ...

class Tensor4I:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[4]]: ...
    def __getitem__(self, arg0: Tuple[int,int,int,int]) -> int: ...
    def __setitem__(self, arg0: Tuple[int,int,int,int], arg1: int) -> None: ...

class ReLU_f2:
    def __init__(self) -> None: ...
    def backward(self, arg0: MatrixF) -> MatrixF: ...
    def forward(self, arg0: MatrixF) -> MatrixF: ...
    def __call__(self, arg0: MatrixF) -> MatrixF: ...

class ReLU_f3:
    def __init__(self) -> None: ...
    def backward(self, *args, **kwargs) -> Any: ...
    def forward(self, *args, **kwargs) -> Any: ...
    def __call__(self, *args, **kwargs) -> Any: ...

class VectorF:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[1]]: ...
    def __getitem__(self, arg0: int) -> float: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...

class VectorI:
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(self, arg0: buffer) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
    def data_size(self) -> int: ...
    def shape(self) -> List[int[1]]: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
