name: Build C++/BLAS

on: [push]

env:
  BUILD_TYPE: Debug
  CXX: g++-10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTENSOR_USE_BLAS=ON -DTENSOR_BUILD_PYTHON_WRAPPER=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF
          cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cd bin && ./tests && cd ..
