name: Build C++/Python

on: [push]

env:
  BUILD_TYPE: Debug
  CXX: g++-10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTENSOR_ENABLE_COVERAGE=ON -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF

      - name: Build C++
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test C++
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cd bin && ./tests && cd ..

      - name: Coverage C++
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: make gcov

      - name: Upload C++ coverage
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"

      - name: Prepare Python package
        shell: bash
        run: |
          cp -r  ${{github.workspace}}/build/bin/libtensor.cpython*.so ${{github.workspace}}/python/src/tensor


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-to-freeze.txt ]; then pip install -r requirements-to-freeze.txt; fi

      - name: Install package
        working-directory: ${{github.workspace}}/python
        run: |
          pip install .

      - name: Test with pytest
        working-directory: ${{github.workspace}}/python
        run: |
          pytest

      - name: Python coverage
        working-directory: ${{github.workspace}}/python
        run: |
          PYTHONPATH=./src pytest --cov-report=xml --cov=src/tensor tests

      - name: Upload Python coverage
        uses: codecov/codecov-action@v1



